import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // MIGHT ADD THEMES LATER 
    // if so, add data-theme="autumn" to html tag
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
